"""add claimed_at for stale claim rescue

Revision ID: 0354f097cd6d
Revises: 1624520ec7fe
Create Date: 2026-07-17 11:59:45.197144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0354f097cd6d'
down_revision: Union[str, None] = '1624520ec7fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'claimed_at')
    # ### end Alembic commands ###
